"""Pure domain model: no I/O and no third-party imports."""

from jobpilot.engine.domain.events import (
    Event,
    EventKind,
    Status,
    normalize_timestamp,
    status_of,
    utc_now,
)
from jobpilot.engine.domain.identity import (
    RoleIdentity,
    canonicalize_role_url,
    identify_role,
    infer_provider,
)
from jobpilot.engine.domain.opportunity import (
    Lane,
    Listing,
    Opportunity,
    opportunity_id,
)
from jobpilot.engine.domain.posting import BoardResult, BoardTarget, Posting, Workplace
from jobpilot.engine.domain.screening import (
    SCREEN,
    SCREEN_VERSION,
    Assessment,
    Check,
    Outcome,
    Screening,
    rules_fingerprint,
    screen,
)
from jobpilot.engine.domain.settings import (
    CompanyRules,
    FitEngine,
    FitSettings,
    LevelRules,
    LocationRules,
    Profile,
    Remote,
    Rules,
    Settings,
    SettingsError,
    Targets,
    parse_settings,
)

__all__ = [
    "SCREEN",
    "SCREEN_VERSION",
    "Assessment",
    "BoardResult",
    "BoardTarget",
    "Check",
    "CompanyRules",
    "Event",
    "EventKind",
    "FitEngine",
    "FitSettings",
    "Lane",
    "LevelRules",
    "Listing",
    "LocationRules",
    "Opportunity",
    "Outcome",
    "Posting",
    "Profile",
    "Remote",
    "RoleIdentity",
    "Rules",
    "Screening",
    "Settings",
    "SettingsError",
    "Status",
    "Targets",
    "Workplace",
    "canonicalize_role_url",
    "identify_role",
    "infer_provider",
    "normalize_timestamp",
    "opportunity_id",
    "parse_settings",
    "rules_fingerprint",
    "screen",
    "status_of",
    "utc_now",
]
